
/* ILocation model: generated by json from API in case of 
loaction searching and converted to typescript*/ 

export interface ILocation {
    Version: number;
    Key: string;
    Type: string;
    Rank: number;
    LocalizedName: string;
    Country: Country;
    AdministrativeArea: AdministrativeArea;
}

export interface Country {
    ID: string;
    LocalizedName: string;
}

export interface AdministrativeArea {
    ID: string;
    LocalizedName: string;
}





